[Interface]
PrivateKey = wD6eZq2fd6a7D2UpM+z8Uu7FnV1xMgU51tIFWuWh42w=
Address = 10.207.186.2/24
DNS = 1.1.1.1, 1.0.0.1

[Peer]
PublicKey = VH0S+6tni0moyHinTJSRzfe9CNoxCctamM2CXqdSKDI=
PresharedKey = 6EqlSG303eN+jpbwvUN1iJzApx/SJAPVRMEWweuMbJk=
Endpoint = 166.203.181.152:51820
AllowedIPs = 0.0.0.0/0, ::0/0
